name: Running code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-reproducibility:
    runs-on: prroai
    permissions: write-all

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run setup script
        run: pip3 install -r requirements.txt

      - name: Run main.py
        id: run_main
        run: |
          python3 main.py
